config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :restaurants do 
    resources :reviews 
  end 

  resources :reviews do 
    resources :likes
  end 
  
  root 'restaurants#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews
	validates :name, presence: true, uniqueness: true, length: {minimum: 3}, format: /\A[A-Z]/
	validates :cuisine, presence: true

	def average_rating
		return calculate_average_rating.round(1) if has_average?
		"No ratings yet"
	end

	private
	def calculate_average_rating
		self.reviews.map { |e| e.rating }.inject(:+).to_f / self.reviews.length
	end

	def has_average?
		!calculate_average_rating.nan?
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	has_many :likes
	validates :rating, presence: true, inclusion: 1..5
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		@review = Review.find(params[:review_id])
		@review.likes.create
		
		render json: { new_like_count: @review.likes.count}
	end 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end 

	def create
		@restaurant = Restaurant.new(params[:restaurant].permit(:name, :cuisine))
		if @restaurant.save 
			flash[:notice] = "Restaurant created"
			redirect_to '/restaurants'
		else
			render 'new'
		end
		
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@restaurant.update(params[:restaurant].permit(:name, :cuisine))
		redirect_to '/restaurants'
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		flash[:notice] = "Deleted"
		redirect_to '/restaurants'
	end 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review = Review.new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review = @restaurant.reviews.new(params[:review].permit(:thoughts, :rating))
		if @review.save
			flash[:notice] = "Review created"
			redirect_to '/restaurants'
		else
			render 'new'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def star_rating(rating)
    return rating unless rating.respond_to?(:round)

    remainder = (5 - rating.round)
    ('★' * rating.round) + ('☆' * remainder)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whoop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<h1>Whoop away</h1>
		<%= link_to 'Add restaurant', new_restaurant_path %>
		<%= link_to 'Register', new_user_registration_path %> 
		<%= link_to 'Sign in', new_user_session_path %>

			<% if user_signed_in? %>
				<h3>Logged in as <%= current_user.email %></h3>
				<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
			<% end %>
	</header>

	
<%= notice %>
	
<%= yield %>

 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
The form has the following errors:
	<% @restaurant.errors.full_messages.each do |message| %>
		<%= message %>
	<% end %> 
<% end %> 

<%= form_for @restaurant do |f| %>
	<%= f.text_field :name, placeholder: 'Enter name of restaurant' %>
	<%= f.text_field :cuisine, placeholder: 'Enter cuisine of restaurant' %>
	<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
Edit restaurant

<%= render 'form' %>

app/views/restaurants/index.html.erb
<html>

<article class='restaurant_name'>

<section>
<table>
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><h2><%= restaurant.name %></h2></td> 
      <td>(<%= restaurant.cuisine %>)</td>
      <td>Average rating: <%= star_rating(restaurant.average_rating) %></td>
    </tr>
      <% restaurant.reviews.each do |review| %>
       <tr>
         <td> <%= "#{review.thoughts} (#{star_rating(review.rating)})" %></td>
          <span class='like_count'>
          <td><%= review.likes.count %> 
          </span> whoops</td>

        <td><div class='whoop'><%= link_to 'Whoop this review', review_likes_path(review), class: 'like-link' %></div></td>
        </tr>
      <% end %>
      <tr>
  <td><%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %></td>
    <td><%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %></td>
    <td><%= link_to "Write review for #{restaurant.name}", new_restaurant_review_path(restaurant) %></td>

  <% end %>
  
  </section>
<% else %>
  No restaurants available
<% end %>
<br>
<%= link_to 'Add a restaurant', new_restaurant_path %>
  </article>
</html>

app/views/restaurants/new.html.erb
Enter a new restaurant

<%= render 'form' %>

app/views/reviews/new.html.erb
<% if @restaurant.errors.any? %>
The form has the following errors:
	<% @restaurant.errors.full_messages.each do |message| %>
		<%= message %>
	<% end %> 
<% end %> 


Enter review for <%= @restaurant.name %>

<%= form_for [@restaurant, @review] do |f| %>
<%= f.label :thoughts %>
<%= f.text_area :thoughts, placeholder: 'Enter your thoughts' %>

<%= f.label :rating %>
<%= f.select :rating, (1..5) %> 

<%= f.submit %>

<% end %> 